### USER registration
POST http://localhost:8000/api/user/auth/register/
Content-Type: application/json

{
  "email": "admin123@example.com",
  "username": "testuser",
  "password": "StrongPassword123!",
  "password2": "StrongPassword123!",
  "first_name": "admin",
  "last_name": "User",
  "role": "admin"
}

### Admin registration
POST http://localhost:8000/api/user/auth/admin/register/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1Nzc2Mjk3LCJpYXQiOjE3NDU3NzI2OTcsImp0aSI6ImIwMjlhYzZiYzg2ODRjZjc4NTJiZTBlZTdiYzY2MzE0IiwidXNlcl9pZCI6N30.ahz3_6MAAlpk97rgDyfM6NkUTG-9C0PtRyR5DlQ1Ks4

{
  "email": "admin@gmail.com",
  "username": "testuser",
  "password": "admin@gmail.com",
  "password2": "admin@gmail.com",
  "first_name": "admin",
  "last_name": "User",
  "role": "admin"
}

### Login
POST http://localhost:8000/api/user/auth/login/
Content-Type: application/json

{
  "email": "tanvirhasanabir8@gmail.com",
  "password": "Abir123@@"
}

### Login
POST http://localhost:8000/api/user/auth/token/refresh/
Content-Type: application/json

{

  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0Njc5Nzc1MSwiaWF0IjoxNzQ1NTg4MTUxLCJqdGkiOiI5Nzg0ODIwZmQ0ZTE0N2ZkYTFlNzIyYzdhZDAzNjIyMCIsInVzZXJfaWQiOjN9.7tZmMAxSwVrHxnlmF9HfRLlkKD5gdM3cIwaeUqVNNKo"

}
### Get Current User Profile
GET http://localhost:8000/api/user/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkxODAyLCJpYXQiOjE3NDU1ODgyMDIsImp0aSI6ImM2ODVjYTA2NGJkMjQwNDdhMDJjMDcxMDIzZmVlOGIwIiwidXNlcl9pZCI6M30.3qtY7lY82LameFZQiyfOJoKCGhtLbrgUwDTQSHXT_1k
### Update Current User Profile
PUT http://localhost:8000/api/user/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkxODAyLCJpYXQiOjE3NDU1ODgyMDIsImp0aSI6ImM2ODVjYTA2NGJkMjQwNDdhMDJjMDcxMDIzZmVlOGIwIiwidXNlcl9pZCI6M30.3qtY7lY82LameFZQiyfOJoKCGhtLbrgUwDTQSHXT_1k

{
  "username": "Tanvir Abir",
  "first_name": "Updated",
  "last_name": "Name",
  "bio": "This is my updated bio"
}


### Update Current User Profile
PUT http://localhost:8000/api/user/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwMzMwLCJpYXQiOjE3NDU1NzY3MzAsImp0aSI6ImQ4N2FiNjgzM2NlZDRkZTdhODNlZGViNDdlYTVmNWQ3IiwidXNlcl9pZCI6MX0.1V1KD21iW7JHXpYI-WyuTuNh6jZOEoOihIFrCmIfils

{
  "username": "updated_username",
  "first_name": "Updated",
  "last_name": "Name",
  "bio": "This is my updated bio"
}

### List All Users
GET http://localhost:8000/api/user/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkxODAyLCJpYXQiOjE3NDU1ODgyMDIsImp0aSI6ImM2ODVjYTA2NGJkMjQwNDdhMDJjMDcxMDIzZmVlOGIwIiwidXNlcl9pZCI6M30.3qtY7lY82LameFZQiyfOJoKCGhtLbrgUwDTQSHXT_1k
### Get User Details
GET http://localhost:8000/api/user/users/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkxODAyLCJpYXQiOjE3NDU1ODgyMDIsImp0aSI6ImM2ODVjYTA2NGJkMjQwNDdhMDJjMDcxMDIzZmVlOGIwIiwidXNlcl9pZCI6M30.3qtY7lY82LameFZQiyfOJoKCGhtLbrgUwDTQSHXT_1k

### Update User Details
PUT http://localhost:8000/api/user/users/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

{
  "username": "updated_username",
  "first_name": "Updated",
  "last_name": "Name",
  "bio": "This is my updated bio"
}

### Delete User
DELETE http://localhost:8000/api/user/users/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

### List All Categories
GET http://localhost:8000/api/inventory/categories/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkxODAyLCJpYXQiOjE3NDU1ODgyMDIsImp0aSI6ImM2ODVjYTA2NGJkMjQwNDdhMDJjMDcxMDIzZmVlOGIwIiwidXNlcl9pZCI6M30.3qtY7lY82LameFZQiyfOJoKCGhtLbrgUwDTQSHXT_1k


### Create New Category (Admin Only)
POST http://localhost:8000/api/inventory/categories/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkxOTQ1LCJpYXQiOjE3NDU1ODgzNDUsImp0aSI6ImIxYjJmNWEwODZmOTQxMmU5N2MzN2IxY2Y3NDFiOTFiIiwidXNlcl9pZCI6M30.YYBoWjcPXO5SRdUWhHp05JiaH1tC4Nq0UHMokzslxWY

{
  "name": "Laptop",
  "description": "Electronic devices and accessories"
}

### Get Category Details
GET http://localhost:8000/api/inventory/categories/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM


### Update Category (Admin Only)
PUT http://localhost:8000/api/inventory/categories/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

{
  "name": "Updated Electronics",
  "description": "Updated description for electronic items"
}

### Update Category (Admin Only)
DELETE http://localhost:8000/api/inventory/categories/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM


### List All Products
GET http://localhost:8000/api/inventory/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

### Create New Product (Admin Only)
POST http://localhost:8000/api/inventory/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

{
  "name": "Smartphone",
  "category": 2,
  "price": 499.99,
  "quantity": 50,
  "description": "Latest smartphone model",
  "stock_threshold": 10,
  "sku": "PHONE-001",
  "is_active": true
}


### Filter Products
GET http://localhost:8000/api/inventory/products/?min_price=100&max_price=500&category=2&low_stock=true&search=smartphone
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

### Get Product Details
GET http://localhost:8000/api/inventory/products/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

### Update Product (Admin Only)
PUT http://localhost:8000/api/inventory/products/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

{
  "name": "Updated Smartphone",
  "price": 449.99,
  "quantity": 45,
  "category": 2,
  "description": "Updated smartphone description"
}

### Get Product Details
GET http://localhost:8000/api/inventory/products/low-stock/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM


### List All Sales (Admin Only)
GET http://localhost:8000/api/inventory/sales/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM


### Create New Sale (Admin Only)
POST http://localhost:8000/api/inventory/sales/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

{
  "product": 1,
  "quantity_sold": 5
}

### Create New Sale (Admin Only)
PUT http://localhost:8000/api/inventory/sales/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTgwNzAzLCJpYXQiOjE3NDU1NzcxMDMsImp0aSI6ImRmMzk5YTQxNWFmMjRkYWVhNjNjOWE1NDBmNTY0OWE0IiwidXNlcl9pZCI6Mn0.fgI2T2XwWBVRcaH8z5WwK-U-xM7tZE2n7ZgIl4fV-PM

{
  "product": 1,
  "quantity_sold": 3
}